apiVersion: v1
kind: Service
metadata:
  name: redforge-virtuoso
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: virtuoso
spec:
  selector:
    app: redforge-virtuoso
  ports:
    - name: http
      port: 8890
      targetPort: 8890
    - name: isql
      port: 1111
      targetPort: 1111
